import React from 'react'
import { Col, Container, Row, ProgressBar } from 'react-bootstrap'

import styles from '../../styles/skills.module.scss'

const Skills = () => {

	return (
		<Container className={styles.container} fluid>
			{/* Generated by https://smooth.ie/blogs/news/svg-wavey-transitions-between-sections */}
			<svg viewBox="0 0 500 150" preserveAspectRatio="none">
				<path d="M0.00,49.98 C180.86,149.50 327.03,0.50 500.00,49.98 L500.00,150.00 L0.00,150.00 Z"></path>
			</svg>

			<Container className={styles.whoiam} fluid>
				<div>
					<h3 id="skillset">Web development <br/> <i className="bi bi-code-slash"></i></h3> 
				</div>
			</Container>
			
			<svg viewBox="0 0 500 150" preserveAspectRatio="none" className={styles.invertedSvg}>
				<path d="M0.00,49.98 C180.86,149.50 327.03,0.50 500.00,49.98 L500.00,150.00 L0.00,150.00 Z"></path>
			</svg>

			<Container className={styles.whaticando} fluid>
				<Row>
					<Col xs={12} lg={3} className={styles.label}>
						<h4><i className="bi bi-kanban"></i> What I can do?</h4>
					</Col>

					<Col xs={12} lg={4} className={styles.progressBars}>
						<div>
							HTML / CSS / JavaScript / JQuery <span>95%</span>
							<ProgressBar variant="danger" now={95} />
						</div>
						<div>
							Node / Express <span>75%</span>
							<ProgressBar variant="success" now={75} />
						</div>
						<div>
							React / React Native <span>95%</span>
							<ProgressBar variant="primary" now={95} />
						</div>
						<div>
							NEXT.js / Gatsby / GraphQL <span>85%</span>
							<ProgressBar variant="dark" now={85} />
						</div>
						<div>
							TypeScript / Angular 9 <span>80%</span>
							<ProgressBar variant="danger" now={80} />
						</div>
						<div>
							MariaDB / MySQL <span>55%</span>
							<ProgressBar variant="warning" now={55} />
						</div>
						<div>
							MongoDB / Mongoose <span>70%</span>
							<ProgressBar variant="success" now={70} />
						</div>
					</Col>

					<Col xs={12} lg={4} className={styles.progressBars}>
						<div>
							PHP / Laravel / Symphony <span>15%</span>
							<ProgressBar variant="warning" now={20} />
						</div>
						<div>
							Python / Flask / Django <span>40%</span>
							<ProgressBar variant="info" now={40} />
						</div>
						<div>
							Wordpress / Prestashop / <span>70%</span>
							<ProgressBar variant="danger" now={70}  />
						</div>
						<div>
							Strapi <span>30%</span>
							<ProgressBar variant="dark" now={30} />
						</div>
						<div>
							Linux services <span>80%</span>
							<ProgressBar variant="success" now={80} />
						</div>
						<div>
							Docker <span>75%</span>
							<ProgressBar variant="primary" now={75} />
						</div>
						<div>
							Jira / Trello / Slack <span>95%</span>
							<ProgressBar variant="dark" now={95} />
						</div>
					</Col>
				</Row>
			</Container>
		</Container>
	)
}

export default Skills